import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Check, Copy, Edit3, RefreshCw, Save, Trash2, Users, X } from "lucide-react";
import { createInstitution, deleteInstitution, deleteInstitutionStudent, generateInstitutionCode, listInstitutions, listInstitutionStudents, setInstitutionStatus, setInstitutionStudentStatus, updateInstitution, updateInstitutionStudent } from "../utils/adminInstitutionStorage";

const emptyForm = () => ({ name:"", access_code:generateInstitutionCode(), student_limit:"30", expires_at:"", status:"active", observations:"" });
const dateText = (value) => value ? new Intl.DateTimeFormat("es-GT", { day:"2-digit", month:"2-digit", year:"numeric" }).format(new Date(`${value}`.slice(0,10)+"T12:00:00")) : "—";
const effectiveStatus = (item) => item.status === "active" && item.expires_at && new Date(item.expires_at) < new Date() ? "expired" : item.status;

export default function AdminInstitutionsSection(){
 const [institutions,setInstitutions]=useState([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [form,setForm]=useState(emptyForm); const [editingId,setEditingId]=useState(null); const [error,setError]=useState(""); const [message,setMessage]=useState("");
 const [selected,setSelected]=useState(null); const [students,setStudents]=useState([]); const [studentsLoading,setStudentsLoading]=useState(false); const [studentEdit,setStudentEdit]=useState(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{setInstitutions(await listInstitutions());}catch(e){setError(e.message||"No se pudieron cargar las instituciones.");}finally{setLoading(false);}},[]);
 useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer);},[load]);
 const stats=useMemo(()=>{const capacity=institutions.reduce((sum,item)=>sum+Number(item.student_limit||0),0);const used=institutions.reduce((sum,item)=>sum+Number(item.registered_students||0),0);return{institutions:institutions.length,students:used,used,available:Math.max(0,capacity-used)};},[institutions]);
 const set=(key,value)=>setForm(current=>({...current,[key]:value}));
 const reset=()=>{setEditingId(null);setForm(emptyForm());};
 const submit=async(event)=>{event.preventDefault();setError("");setMessage("");if(!form.name.trim()||!form.access_code.trim()||!form.student_limit||!form.expires_at){setError("Completa nombre, código, alumnos contratados y vencimiento.");return;}setSaving(true);try{if(editingId){await updateInstitution(editingId,form);setMessage("Institución actualizada.");}else{await createInstitution(form);setMessage("Institución creada correctamente.");}reset();await load();}catch(e){setError(e.message||"No se pudo guardar la institución.");}finally{setSaving(false);}};
 const edit=(item)=>{setEditingId(item.id);setForm({name:item.name||"",access_code:item.access_code||"",student_limit:String(item.student_limit||""),expires_at:String(item.expires_at||"").slice(0,10),status:item.status||"active",observations:item.notes||""});document.querySelector(".admin-institution-form")?.scrollIntoView({behavior:"smooth",block:"center"});};
 const changeStatus=async(item,status)=>{setError("");try{await setInstitutionStatus(item.id,status);await load();}catch(e){setError(e.message||"No se pudo cambiar el estado.");}};
 const remove=async(item)=>{if(!confirm(`¿Eliminar ${item.name}? También se eliminarán sus datos relacionados si Supabase lo permite.`))return;setError("");try{await deleteInstitution(item.id);await load();}catch(e){setError(e.message||"No se pudo eliminar la institución.");}};
 const openStudents=async(item)=>{setSelected(item);setStudentsLoading(true);setStudentEdit(null);try{setStudents(await listInstitutionStudents(item.id));}catch(e){setError(e.message||"No se pudieron cargar los alumnos.");setSelected(null);}finally{setStudentsLoading(false);}};
 const refreshStudents=async()=>{if(selected)setStudents(await listInstitutionStudents(selected.id));};
 const saveStudent=async()=>{try{await updateInstitutionStudent(studentEdit.id,studentEdit);setStudentEdit(null);await refreshStudents();await load();}catch(e){setError(e.message||"No se pudo actualizar el alumno.");}};
 const studentStatus=async(student,status)=>{try{await setInstitutionStudentStatus(student.id,status);await refreshStudents();}catch(e){setError(e.message||"No se pudo cambiar el estado del alumno.");}};
 const removeStudent=async(student)=>{if(!confirm(`¿Eliminar al alumno ${student.full_name}?`))return;try{await deleteInstitutionStudent(student.id);await refreshStudents();await load();}catch(e){setError(e.message||"No se pudo eliminar el alumno.");}};
 return <section className="admin-institutions-section">
  <div className="admin-section-heading"><div><span className="admin-kicker"><Building2 size={18}/> Instituciones</span><h2>Administración de instituciones</h2><p>Crea colegios, controla sus cupos y administra sus alumnos.</p></div><button className="admin-ghost-button" onClick={load} disabled={loading}><RefreshCw size={17}/> Actualizar</button></div>
  <div className="admin-stats admin-institution-stats"><article><strong>{stats.institutions}</strong><span>Total de instituciones</span></article><article><strong>{stats.students}</strong><span>Total de alumnos</span></article><article><strong>{stats.used}</strong><span>Cupos utilizados</span></article><article><strong>{stats.available}</strong><span>Cupos disponibles</span></article></div>
  <form className="admin-generator admin-institution-form" onSubmit={submit}><div className="admin-generator-title"><Building2 size={24}/><div><h2>{editingId?"Editar institución":"Crear institución"}</h2><p>El código se genera automáticamente y puedes editarlo antes de guardar.</p></div>{editingId&&<button type="button" className="admin-ghost-button" onClick={reset}><X size={17}/> Cancelar</button>}</div>
   <div className="admin-form-grid"><label>Nombre del colegio<input value={form.name} onChange={e=>set("name",e.target.value)} maxLength={100}/></label><label>Código de acceso<div className="admin-code-field"><input value={form.access_code} onChange={e=>set("access_code",e.target.value.toUpperCase())} maxLength={40}/><button type="button" onClick={()=>set("access_code",generateInstitutionCode(form.name))}>Generar</button></div></label><label>Alumnos contratados<input type="number" min="1" value={form.student_limit} onChange={e=>set("student_limit",e.target.value)}/></label><label>Fecha de vencimiento<input type="date" value={form.expires_at} onChange={e=>set("expires_at",e.target.value)}/></label><label>Estado<select value={form.status} onChange={e=>set("status",e.target.value)}><option value="active">Activa</option><option value="suspended">Suspendida</option><option value="expired">Vencida</option></select></label><label>Observaciones<textarea value={form.observations} onChange={e=>set("observations",e.target.value)} placeholder="Información opcional" maxLength={1000}/></label></div>
   <button className="admin-primary-button" disabled={saving}><Save size={17}/> {saving?"Guardando…":editingId?"Guardar cambios":"Crear institución"}</button>{message&&<div className="admin-message success">{message}</div>}{error&&<div className="admin-message error">{error}</div>}
  </form>
  <section className="admin-list-card"><div className="admin-list-header"><div><h2>Instituciones</h2><p>Control de cupos, vencimientos, estado y alumnos.</p></div></div><div className="admin-table-wrap"><table className="admin-table admin-institutions-table"><thead><tr><th>Nombre</th><th>Código</th><th>Contratados</th><th>Registrados</th><th>Disponibles</th><th>Vencimiento</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{loading?<tr><td colSpan="8">Cargando…</td></tr>:institutions.length===0?<tr><td colSpan="8">Todavía no hay instituciones.</td></tr>:institutions.map(item=>{const status=effectiveStatus(item);return <tr key={item.id}><td><strong>{item.name}</strong></td><td><code>{item.access_code}</code><button className="admin-copy-inline" onClick={()=>navigator.clipboard?.writeText(item.access_code)} title="Copiar"><Copy size={14}/></button></td><td>{item.student_limit}</td><td>{item.registered_students}</td><td>{Math.max(0,Number(item.student_limit)-Number(item.registered_students))}</td><td className="admin-date">{dateText(item.expires_at)}</td><td><span className={`admin-status ${status}`}>{status==="active"?"Activa":status==="suspended"?"Suspendida":"Vencida"}</span></td><td className="admin-actions admin-institution-actions"><button onClick={()=>edit(item)}><Edit3 size={15}/> Editar</button>{item.status==="active"?<button onClick={()=>changeStatus(item,"suspended")}>⛔ Suspender</button>:<button onClick={()=>changeStatus(item,"active")}><Check size={15}/> Activar</button>}<button onClick={()=>remove(item)}><Trash2 size={15}/> Eliminar</button><button onClick={()=>openStudents(item)}><Users size={15}/> Ver alumnos</button></td></tr>})}</tbody></table></div></section>
  {selected&&<div className="admin-student-backdrop" role="dialog" aria-modal="true"><section className="admin-student-modal"><div className="admin-list-header"><div><span className="admin-kicker"><Users size={18}/> Alumnos</span><h2>{selected.name}</h2><p>{students.length} de {selected.student_limit} cupos utilizados</p></div><button className="admin-ghost-button" onClick={()=>setSelected(null)}><X size={18}/> Cerrar</button></div><div className="admin-table-wrap"><table className="admin-table admin-students-table"><thead><tr><th>Avatar</th><th>Nombre</th><th>Código</th><th>Grado</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{studentsLoading?<tr><td colSpan="6">Cargando…</td></tr>:students.length===0?<tr><td colSpan="6">No hay alumnos registrados.</td></tr>:students.map(student=><tr key={student.id}>{studentEdit?.id===student.id?<><td><img className="admin-student-avatar" src={studentEdit.avatar||"/assets/avatar-1.png"}/></td><td><input value={studentEdit.full_name} onChange={e=>setStudentEdit(v=>({...v,full_name:e.target.value}))}/></td><td><input value={studentEdit.student_code} onChange={e=>setStudentEdit(v=>({...v,student_code:e.target.value.toUpperCase()}))}/></td><td><select value={studentEdit.grade} onChange={e=>setStudentEdit(v=>({...v,grade:e.target.value}))}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}.º</option>)}</select></td><td><select value={studentEdit.status} onChange={e=>setStudentEdit(v=>({...v,status:e.target.value}))}><option value="active">Activo</option><option value="inactive">Inactivo</option></select></td><td className="admin-actions"><button onClick={saveStudent}><Save size={15}/> Guardar</button><button onClick={()=>setStudentEdit(null)}>Cancelar</button></td></>:<><td><img className="admin-student-avatar" src={student.avatar||"/assets/avatar-1.png"}/></td><td><strong>{student.full_name}</strong></td><td><code>{student.student_code}</code></td><td>{student.grade}.º</td><td><span className={`admin-status ${student.status}`}>{student.status==="active"?"Activo":"Inactivo"}</span></td><td className="admin-actions admin-institution-actions"><button onClick={()=>setStudentEdit({...student})}><Edit3 size={15}/> Editar</button>{student.status==="active"?<button onClick={()=>studentStatus(student,"inactive")}>Desactivar</button>:<button onClick={()=>studentStatus(student,"active")}>Reactivar</button>}<button onClick={()=>removeStudent(student)}><Trash2 size={15}/> Eliminar</button></td></>}</tr>)}</tbody></table></div></section></div>}
 </section>;
}
