import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Volume2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { updateUnitProgress } from "../utils/progressManager";
import "../styles/english-animals-unit.css";
const animals=[
 {word:'LION',meaning:'León',emoji:'🦁',phrase:'The lion is strong.'},{word:'ELEPHANT',meaning:'Elefante',emoji:'🐘',phrase:'The elephant is big.'},{word:'MONKEY',meaning:'Mono',emoji:'🐒',phrase:'The monkey can climb.'},{word:'TIGER',meaning:'Tigre',emoji:'🐯',phrase:'The tiger is fast.'},{word:'GIRAFFE',meaning:'Jirafa',emoji:'🦒',phrase:'The giraffe is tall.'},{word:'ZEBRA',meaning:'Cebra',emoji:'🦓',phrase:'The zebra has stripes.'},{word:'BIRD',meaning:'Pájaro',emoji:'🦜',phrase:'The bird can fly.'},{word:'FROG',meaning:'Rana',emoji:'🐸',phrase:'The frog can jump.'},{word:'DOG',meaning:'Perro',emoji:'🐶',phrase:'The dog is friendly.'},{word:'CAT',meaning:'Gato',emoji:'🐱',phrase:'The cat is small.'}
];
export default function EnglishAnimalsLesson(){const navigate=useNavigate();const [index,setIndex]=useState(0);const item=animals[index];const speak=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(item.word);u.lang='en-US';u.rate=.8;speechSynthesis.speak(u)};const next=()=>{if(index<animals.length-1)setIndex(index+1);else{updateUnitProgress('english','beginner',4,35);navigate('/english/beginner/unit/4/game')}};return <main className="animals-screen lesson-mode"><header className="animals-topbar compact"><button onClick={()=>navigate('/english/beginner/unit/4')}><ArrowLeft/> Aventura</button><div><span>Lección Animals</span><strong>{index+1} de {animals.length}</strong></div><div className="lesson-counter">🐾 {index+1}/10</div></header><div className="animals-progress"><span style={{width:`${((index+1)/animals.length)*100}%`}}/></div><section className="animal-lesson-stage"><motion.article key={item.word} className="animal-card" initial={{opacity:0,y:30,rotate:-2}} animate={{opacity:1,y:0,rotate:0}}><div className="animal-emoji">{item.emoji}</div><span>{item.meaning}</span><h1>{item.word}</h1><button className="animal-sound" onClick={speak}><Volume2/> Escuchar pronunciación</button><p>{item.phrase}</p></motion.article><div className="lesson-dots">{animals.map((_,i)=><span key={i} className={i===index?'active':''}/>)}</div><button className="animals-primary" onClick={next}>{index===animals.length-1?'Ir al rescate':'Siguiente animal'} <ArrowRight/></button></section></main>}
