import { useMemo,useState } from "react";
import { AnimatePresence,motion } from "framer-motion";
import { ArrowLeft,CheckCircle2,Heart,PawPrint,XCircle } from "lucide-react";
import { useNavigate } from "react-router-dom";
import "../styles/english-animals-unit.css";
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const questions=[
 {p:'¿Cómo se dice león en inglés?',e:'🦁',a:'LION',o:['LION','TIGER','CAT']},{p:'Selecciona ELEPHANT',e:'🐘',a:'ELEPHANT',o:['MONKEY','ELEPHANT','GIRAFFE']},{p:'¿Qué significa MONKEY?',e:'🐒',a:'MONO',o:['RANA','MONO','PERRO']},{p:'¿Cómo se dice tigre en inglés?',e:'🐯',a:'TIGER',o:['LION','ZEBRA','TIGER']},{p:'Selecciona GIRAFFE',e:'🦒',a:'GIRAFFE',o:['GIRAFFE','ELEPHANT','BIRD']},{p:'¿Qué significa ZEBRA?',e:'🦓',a:'CEBRA',o:['JIRAFA','CEBRA','TIGRE']},{p:'Completa: The bird can ___',e:'🦜',a:'FLY',o:['SWIM','FLY','CLIMB']},{p:'¿Cómo se dice rana en inglés?',e:'🐸',a:'FROG',o:['DOG','FROG','CAT']}
];
export default function EnglishAnimalsQuiz(){const navigate=useNavigate();const qs=useMemo(()=>shuffle(questions).map(q=>({...q,o:shuffle(q.o)})),[]);const [i,setI]=useState(0),[sel,setSel]=useState(''),[checked,setChecked]=useState(false),[score,setScore]=useState(0),[hearts,setHearts]=useState(3);const q=qs[i],correct=sel===q.a;const check=()=>{if(!sel||checked)return;setChecked(true);if(correct)setScore(v=>v+1);else setHearts(v=>Math.max(0,v-1))};const next=()=>{if(i===qs.length-1){navigate('/english/beginner/unit/4/reward',{state:{score:score+(correct?1:0),total:qs.length,hearts:Math.max(0,hearts-(!correct?1:0))}});return}setI(v=>v+1);setSel('');setChecked(false)};return <main className="animals-screen quiz-mode"><header className="animals-topbar compact"><button onClick={()=>navigate('/english/beginner/unit/4/game')}><ArrowLeft/> Mini juego</button><div><span>Evaluación Animals</span><strong>Reto {i+1} de {qs.length}</strong></div><div className="animal-hearts">{[1,2,3].map(h=><Heart key={h} fill={h<=hearts?'currentColor':'none'}/>)}</div></header><div className="animals-progress"><span style={{width:`${((i+1)/qs.length)*100}%`}}/></div><section className="animal-quiz-stage"><AnimatePresence mode="wait"><motion.article key={i} className="animal-quiz-card" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-30}}><span className="quiz-tag"><PawPrint/> Insignia de explorador</span><div className="quiz-animal">{q.e}</div><h1>{q.p}</h1><div className="animal-options">{q.o.map(o=><button key={o} disabled={checked} className={`${sel===o?'selected':''} ${checked&&o===q.a?'correct':''} ${checked&&sel===o&&o!==q.a?'incorrect':''}`} onClick={()=>setSel(o)}>{o}{checked&&o===q.a&&<CheckCircle2/>}{checked&&sel===o&&o!==q.a&&<XCircle/>}</button>)}</div>{!checked?<button className="animals-primary" disabled={!sel} onClick={check}>Comprobar</button>:<div className={`quiz-feedback ${correct?'good':'bad'}`}><strong>{correct?'¡Excelente!':'Casi lo logras'}</strong><span>La respuesta correcta es {q.a}.</span><button className="animals-primary" onClick={next}>{i===qs.length-1?'Ver recompensa':'Siguiente reto'}</button></div>}</motion.article></AnimatePresence></section></main>}
