import { useEffect, useMemo, useRef } from "react";
import { motion } from "framer-motion";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { Award, Download, Home, Map, Sparkles, Star } from "lucide-react";
import { getIntermediateUnit } from "../data/englishIntermediateData";
import { completeUnit } from "../utils/progressManager";
import { getProfile } from "../utils/profileStorage";
import "../styles/english-intermediate.css";

export default function EnglishIntermediateReward(){
 const navigate=useNavigate(); const location=useLocation(); const {unitId}=useParams(); const unit=getIntermediateUnit(unitId); const saved=useRef(false); const score=Number(location.state?.score||unit.quiz.length),total=Number(location.state?.total||unit.quiz.length),hearts=Number(location.state?.hearts??3); const pct=Math.round(score/total*100); const stars=useMemo(()=>pct>=90?3:pct>=70?2:1,[pct]);
 useEffect(()=>{if(saved.current)return;saved.current=true;completeUnit("english","intermediate",unit.id,stars,unit.xp+stars*20)},[unit.id,stars]);
 const diploma=()=>{const name=getProfile()?.name?.trim()||"Estudiante EduPlay";const c=document.createElement("canvas");c.width=1600;c.height=1100;const x=c.getContext("2d");const g=x.createLinearGradient(0,0,1600,1100);g.addColorStop(0,"#061f56");g.addColorStop(.5,"#123d91");g.addColorStop(1,"#40126b");x.fillStyle=g;x.fillRect(0,0,1600,1100);x.strokeStyle="#ffd75a";x.lineWidth=22;x.strokeRect(38,38,1524,1024);x.strokeStyle="#fff2ad";x.lineWidth=4;x.strokeRect(72,72,1456,956);x.textAlign="center";x.fillStyle="#ffd75a";x.font="900 74px Georgia";x.fillText("EDUPLAY",800,170);x.fillStyle="white";x.font="700 35px Georgia";x.fillText("DIPLOMA DE ENGLISH INTERMEDIATE",800,250);x.font="500 30px Arial";x.fillText("Se certifica que",800,350);x.fillStyle="#fff2a3";x.font="900 68px Georgia";x.fillText(name,800,455);x.fillStyle="white";x.font="500 29px Arial";x.fillText("completó con éxito las cuatro aventuras del nivel Intermedio",800,550);x.font="700 27px Arial";x.fillText("Verb To Be • Present Simple • Daily Routine • Final Challenge",800,625);x.fillStyle="#ffd75a";x.font="900 54px Arial";x.fillText("★ ★ ★",800,735);x.fillStyle="white";x.font="600 25px Arial";x.fillText(`Resultado final: ${score}/${total} · ${pct}%`,800,810);x.font="500 22px Arial";x.fillText(new Date().toLocaleDateString("es-GT",{year:"numeric",month:"long",day:"numeric"}),800,930);const a=document.createElement("a");a.download=`Diploma_English_Intermediate_${name.replace(/\s+/g,"_")}.png`;a.href=c.toDataURL("image/png");a.click()};
 const final=unit.id===4;
 return <main className={`ei-stage ei-stage-${unit.theme}`}><button className="ei-worlds-back" onClick={()=>navigate("/english")}><Home/> Volver a mundos</button><motion.section className="ei-reward-card" initial={{scale:.6,opacity:0}} animate={{scale:1,opacity:1}}><Sparkles className="ei-spark"/><div className="ei-reward-icon">{final?"🏆":unit.icon}</div><small>{final?"NIVEL COMPLETADO":"MISIÓN COMPLETADA"}</small><h1>{final?"¡English Intermediate superado!":`¡${unit.title} completado!`}</h1><div className="ei-stars">{[1,2,3].map(s=><Star key={s} fill={s<=stars?"currentColor":"none"}/>)}</div><p>Resultado: <b>{score}/{total}</b> · +{unit.xp+stars*20} XP</p>{final&&<button className="ei-diploma" onClick={diploma}><Download/> Descargar diploma premium</button>}<div className="ei-reward-actions"><button onClick={()=>navigate("/english/intermediate")}><Map/> Ver mapa</button><button className="ei-primary" onClick={()=>navigate(final?"/english":"/english/intermediate")}><Award/> {final?"Ver nivel avanzado":"Continuar"}</button><button onClick={()=>navigate("/english")}><Home/> Niveles de English</button></div></motion.section></main>
}
