import { useEffect, useMemo, useRef, useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Award, BookOpen, CheckCircle2, ChevronRight, Download, Headphones, Heart, Home, Mic2, RotateCcw, Sparkles, Star, Volume2 } from "lucide-react";
import { motion } from "framer-motion";
import { getLanguageLevel, getLanguageUnit } from "../data/languageWorldData";
import { completeUnit, getLevelProgress, updateUnitProgress } from "../utils/progressManager";
import { getProfile } from "../utils/profileStorage";
import { useDemoAccount } from "../utils/demoAccess";
import "../styles/language-lesson.css";

const progressByStage={presentation:5,intro:20,examples:35,practice:50,game:68,quiz:85,result:92,reward:100};
const routeFor=(level,id,stage)=>({presentation:`/language/${level}/unit/${id}/lesson`,intro:`/language/${level}/unit/${id}/examples`,examples:`/language/${level}/unit/${id}/practice`,practice:`/language/${level}/unit/${id}/game`,game:`/language/${level}/unit/${id}/quiz`}[stage]);
const normalize=(value)=>String(value||"").trim().toLocaleLowerCase("es").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ");
const speak=(text)=>{if(!window.speechSynthesis)return false;window.speechSynthesis.cancel();const voice=new SpeechSynthesisUtterance(text);voice.lang="es-GT";voice.rate=.88;window.speechSynthesis.speak(voice);return true};

function Shell({unit,level,stage,children}){const navigate=useNavigate();return <main className={`language-lesson-screen language-stage-${stage} language-mechanic-${unit.mechanic}`} style={{"--language-accent":unit.color}}><div className="language-lesson-stars" aria-hidden="true">a ✦ b ✧ c ✦ ñ ✧</div><div className="language-scene-decor" aria-hidden="true"><span>📚</span><span>✒️</span><span>🔤</span><span>📜</span><span>✨</span></div><header className="language-lesson-top"><button onClick={()=>navigate(`/language/${level}`)}><ArrowLeft/> Biblioteca</button><div><span>Comunicación y Lenguaje · {getLanguageLevel(level).title}</span><b>{unit.title}</b></div><div className="language-stage-progress"><span>Página {progressByStage[stage]}%</span><i><b style={{width:`${progressByStage[stage]}%`}}/></i></div></header>{children}</main>}
function Continue({onClick,label="Continuar"}){return <button className="language-primary" onClick={onClick}>{label}<ChevronRight/></button>}
function ReadButton({text}){const[available,setAvailable]=useState(true);return <button className="language-read" onClick={()=>setAvailable(speak(text))}><Volume2/>{available?"Escuchar lectura":"Lectura no disponible"}</button>}

export default function LanguageLessonStage({stage}){
  const {level="beginner",unitId="1"}=useParams(),unit=getLanguageUnit(level,unitId),navigate=useNavigate(),location=useLocation(),demo=useDemoAccount();
  const validUnit=getLanguageLevel(level).units.some((item)=>item.id===Number(unitId));
  const beginnerDone=getLevelProgress("language","beginner").completedUnits.length,intermediateDone=getLevelProgress("language","intermediate").completedUnits.length,current=getLevelProgress("language",level);
  const beginnerTotal=getLanguageLevel("beginner").units.length,intermediateTotal=getLanguageLevel("intermediate").units.length;
  const levelAllowed=demo||level==="beginner"||(level==="intermediate"&&beginnerDone>=beginnerTotal)||(level==="advanced"&&beginnerDone>=beginnerTotal&&intermediateDone>=intermediateTotal),unitAllowed=validUnit&&(demo||(levelAllowed&&current.unlockedUnits.includes(unit.id)));
  useEffect(()=>{if(!unitAllowed)navigate(`/language/${level}`,{replace:true})},[level,navigate,unitAllowed]);
  useEffect(()=>{if(unitAllowed&&stage!=="reward")updateUnitProgress("language",level,unit.id,progressByStage[stage])},[level,stage,unit.id,unitAllowed]);
  if(!unitAllowed)return null;const next=()=>navigate(routeFor(level,unit.id,stage));
  if(stage==="presentation")return <Shell {...{unit,level,stage}}><section className="language-cinematic"><motion.div className="language-magic-book" initial={{rotateY:80,scale:.7}} animate={{rotateY:0,scale:1}} transition={{duration:.8,type:"spring"}}><img src={unit.image} alt=""/><div className="language-book-glow"/><span>🕊️</span></motion.div><motion.div initial={{opacity:0,x:60}} animate={{opacity:1,x:0}} transition={{delay:.4}}><small>CAPÍTULO {unit.id} · LUMI TE ACOMPAÑA</small><h1>{unit.title}</h1><p>{unit.subtitle}</p><blockquote>“Las palabras son llaves. Hoy encontraremos una nueva.”</blockquote><ul><li><BookOpen/> Libro interactivo</li><li><Headphones/> Lectura en voz alta opcional</li><li><Sparkles/> {unit.gameTitle}</li><li><Award/> Pluma de Historia coleccionable</li></ul><Continue onClick={next} label="Abrir el libro"/></motion.div></section></Shell>;
  if(stage==="intro")return <Shell {...{unit,level,stage}}><section className="language-open-book"><div className="language-book-ribbon"><span>🕊️</span> APRENDEMOS CON LUMI <span>✦</span></div><div className="language-book-pages"><article><div className="language-chapter-badge">CAPÍTULO {unit.id}</div><small>✦ PÁGINA DE DESCUBRIMIENTO</small><h1>{unit.title}</h1>{unit.intro.slice(0,2).map((p,i)=><motion.p key={i} initial={{opacity:0,x:-20}} animate={{opacity:1,x:0}} transition={{delay:i*.35}}>{p}</motion.p>)}<div className="language-ink-signature">Lumi dejó esta pista para ti ✒</div></article><article><div className="language-page-corner">ABC</div><img src={unit.image} alt=""/><p>{unit.intro[2]}</p><ReadButton text={unit.intro.join(" ")}/><div className="language-page-trinkets" aria-hidden="true">📖 🪶 ✨</div></article></div><Continue onClick={next} label="Pasar la página"/></section></Shell>;
  if(stage==="examples")return <Shell {...{unit,level,stage}}><section className="language-example-stage"><div className="language-theater-curtain left"/><div className="language-theater-curtain right"/><header><div className="language-theater-lights" aria-hidden="true">● ● ● ● ● ● ●</div><span>🎭 TEATRO DE EJEMPLOS</span><h1>Las palabras cobran vida</h1><div className="language-lumi-theater"><b>🕊️</b><p>Observa cada escena, escucha su sonido y descubre la pista.</p></div><ReadButton text={unit.examples.map(e=>`${e.title}. ${e.text}`).join(" ")}/></header><div className="language-example-cast">{unit.examples.map((example,index)=><motion.article key={example.title} initial={{opacity:0,scale:.72,y:70}} animate={{opacity:1,scale:1,y:0}} transition={{delay:index*.14,type:"spring"}}><span className="language-scene-number">ESCENA {index+1}</span><b>{example.visual}</b><h2>{example.title}</h2><p>{example.text}</p><button onClick={()=>speak(`${example.visual}. ${example.text}`)} aria-label={`Escuchar ${example.title}`}><Volume2/></button><i aria-hidden="true"/></motion.article>)}</div><div className="language-footlights" aria-hidden="true">● ● ● ● ● ● ● ● ● ● ● ●</div><Continue onClick={next} label="Entrar al taller"/></section></Shell>;
  if(stage==="practice")return <LanguageChallenge unit={unit} level={level} stage={stage} items={unit.practice} guided onDone={next}/>;
  if(stage==="game")return <LanguageChallenge unit={unit} level={level} stage={stage} items={unit.game} onDone={next}/>;
  if(stage==="quiz")return <LanguageQuiz unit={unit} level={level} stage={stage}/>;
  if(stage==="result")return <LanguageResult unit={unit} level={level} stage={stage} state={location.state}/>;
  return <LanguageReward unit={unit} level={level} stage="reward" state={location.state}/>;
}

function LanguageChallenge({unit,level,stage,items,guided=false,onDone}){const[index,setIndex]=useState(0),[picked,setPicked]=useState(""),[typed,setTyped]=useState(""),[score,setScore]=useState(0);const item=items[index],writing=unit.mechanic==="story-editor"||unit.mechanic==="newsroom",correct=normalize(writing?typed:picked)===normalize(item.answer);const choose=(value)=>{setPicked(value);if(normalize(value)===normalize(item.answer)&&!picked)setScore(score+1)};const check=()=>setPicked(typed);const next=()=>{if(index===items.length-1)onDone();else{setIndex(index+1);setPicked("");setTyped("")}};return <Shell {...{unit,level,stage}}><section className={`language-workshop ${guided?"guided":"game"}`}><header><div>{stage==="game"?<Mic2/>:<Sparkles/>}</div><span>{guided?"TALLER GUIADO · SIN PENALIZACIÓN":unit.gameTitle.toUpperCase()}</span><strong>{index+1}/{items.length}</strong></header>{!guided&&<div className="language-game-hud"><span>🏆 Puntos: {score}</span><div>{items.map((_,i)=><i key={i} className={i<index?"complete":i===index?"current":""}/>)}</div><span>🪶 Reto {index+1}</span></div>}<div className="language-workshop-scene"><div className="language-activity-props" aria-hidden="true"><span>{guided?"📝":"🎯"}</span><span>{unit.mechanic==="syllable-wheel"?"🎡":unit.mechanic==="word-builder"?"🔤":unit.mechanic==="newsroom"?"📰":unit.mechanic==="radio-studio"?"🎙️":"📚"}</span><span>{guided?"✏️":"🏅"}</span></div><div className="language-lumi-guide">🕊️<span>{guided?"Prueba, revisa y vuelve a intentar.":"¡Tu historia está cobrando vida!"}</span></div><div className="language-task-scroll"><small>{guided?"MISIÓN DEL TALLER":"DESAFÍO DEL JUEGO"}</small><h1>{item.prompt}</h1>{stage==="game"&&<button className="language-listen-clue" onClick={()=>speak(item.prompt)}><Volume2/> Escuchar pista</button>}</div>{writing?<div className="language-writing"><div className="language-typewriter-bar">● ● ● MÁQUINA DE PALABRAS</div><textarea value={typed} onChange={e=>setTyped(e.target.value)} placeholder="Escribe tu respuesta aquí…"/><button onClick={check}>Comprobar</button></div>:<div className="language-word-tiles">{item.options.map((option,i)=><motion.button key={`${option}-${i}`} className={picked?(normalize(option)===normalize(item.answer)?"correct":option===picked?"wrong":""):""} onClick={()=>choose(option)} whileHover={{y:-7,rotate:i%2?1:-1}} whileTap={{scale:.96}}><span>{String.fromCharCode(65+i)}</span>{option}</motion.button>)}</div>}{picked&&<motion.div initial={{scale:.8,opacity:0}} animate={{scale:1,opacity:1}} className={`language-feedback ${correct?"ok":"retry"}`}>{correct?<><CheckCircle2/> ¡La tinta brilló! Respuesta correcta.</>:<><RotateCcw/> Lumi dejó una pista. Revisa y prueba otra vez.</>}</motion.div>}{correct&&<Continue onClick={next} label={index===items.length-1?(guided?"Ir a la aventura":"Ir a la evaluación"):"Siguiente página"}/>}</div></section></Shell>}

function LanguageQuiz({unit,level,stage}){const navigate=useNavigate();const[index,setIndex]=useState(0),[score,setScore]=useState(0),[hearts,setHearts]=useState(3),[picked,setPicked]=useState("");const item=unit.quiz[index];const choose=(value)=>{if(picked)return;setPicked(value);if(normalize(value)===normalize(item.answer))setScore(score+1);else setHearts(Math.max(0,hearts-1))};const next=()=>{if(index===unit.quiz.length-1||hearts===0)navigate(`/language/${level}/unit/${unit.id}/result`,{state:{score,total:unit.quiz.length}});else{setIndex(index+1);setPicked("")}};return <Shell {...{unit,level,stage}}><section className="language-quiz"><div className="language-quiz-emblem">✒️<span>EVALUACIÓN</span></div><header><span>EL GRAN RETO DEL LIBRO · {index+1}/{unit.quiz.length}</span><div>{[0,1,2].map(i=><Heart key={i} fill={i<hearts?"currentColor":"none"}/>)}</div></header><div className="language-quill-line"><i style={{width:`${(index+1)/unit.quiz.length*100}%`}}/></div><div className="language-quiz-layout"><aside><div className="language-quiz-narrator">🕊️</div><p>Lumi custodia el Gran Libro. Demuestra lo que aprendiste para encender su sello.</p><ReadButton text={item.question}/><div className="language-quiz-score">Aciertos <b>{score}</b></div></aside><div className="language-quiz-question"><small>PREGUNTA {String(index+1).padStart(2,"0")}</small><h1>{item.question}</h1><div className="language-word-tiles">{item.options.map((option,i)=><button key={`${option}-${i}`} className={picked?(normalize(option)===normalize(item.answer)?"correct":option===picked?"wrong":""):""} onClick={()=>choose(option)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{picked&&<Continue onClick={next} label={index===unit.quiz.length-1||hearts===0?"Cerrar el libro":"Siguiente reto"}/>}</div></div></section></Shell>}

function LanguageResult({unit,level,stage,state}){const navigate=useNavigate(),score=Number(state?.score||0),total=Number(state?.total||unit.quiz.length),pct=Math.round(score/total*100);return <Shell {...{unit,level,stage}}><section className="language-result"><motion.div className="language-ink-seal" initial={{scale:2,opacity:0}} animate={{scale:1,opacity:1}}>✒️<span>{pct}%</span></motion.div><small>EL CONSEJO DE LOS LIBROS HA LEÍDO TU AVENTURA</small><h1>{pct>=80?"¡Tu historia brilló!":pct>=60?"¡Gran capítulo!":"Toda gran historia mejora al revisarla"}</h1><p>Superaste <b>{score} de {total}</b> desafíos.</p><div><span>🪶 Pluma de Historia</span><span>⭐ {pct>=90?3:pct>=70?2:1} estrellas</span><span>✨ +{unit.xp} XP</span></div><Continue onClick={()=>navigate(`/language/${level}/unit/${unit.id}/reward`,{state:{score,total}})} label="Revelar recompensa"/></section></Shell>}

function LanguageReward({unit,level,stage,state}){const navigate=useNavigate(),once=useRef(false),score=Number(state?.score||unit.quiz.length),total=Number(state?.total||unit.quiz.length),pct=Math.round(score/total*100),stars=pct>=90?3:pct>=70?2:1,final=unit.id===getLanguageLevel(level).units.length;useEffect(()=>{if(once.current)return;once.current=true;completeUnit("language",level,unit.id,stars,unit.xp+stars*20)},[level,stars,unit.id,unit.xp]);const feather=useMemo(()=>["Pluma del Alfabeto","Pluma del Narrador","Pluma del Cronista"][getLanguageLevel(level).number-1], [level]);const diploma=()=>{const name=getProfile()?.name||"Estudiante EduPlay",canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=1600;canvas.height=1100;const g=ctx.createLinearGradient(0,0,1600,1100);g.addColorStop(0,"#24144f");g.addColorStop(.5,"#7a285e");g.addColorStop(1,"#087f8c");ctx.fillStyle=g;ctx.fillRect(0,0,1600,1100);ctx.strokeStyle="#f4d17b";ctx.lineWidth=25;ctx.strokeRect(45,45,1510,1010);ctx.textAlign="center";ctx.fillStyle="#f4d17b";ctx.font="900 70px Georgia";ctx.fillText("EDUPLAY · BIBLIOTECA VIVA",800,180);ctx.fillStyle="white";ctx.font="700 46px Georgia";ctx.fillText(`DIPLOMA DE COMUNICACIÓN Y LENGUAJE`,800,310);ctx.font="30px Arial";ctx.fillText("Se reconoce a",800,420);ctx.fillStyle="#fff0b0";ctx.font="900 74px Georgia";ctx.fillText(name,800,545);ctx.fillStyle="white";ctx.font="28px Arial";ctx.fillText(`por completar los siete capítulos del nivel ${getLanguageLevel(level).title}`,800,660);ctx.fillStyle="#f4d17b";ctx.font="900 58px Arial";ctx.fillText("✦  🪶  ✦",800,785);ctx.fillStyle="white";ctx.font="24px Arial";ctx.fillText(new Date().toLocaleDateString("es-GT"),800,920);const link=document.createElement("a");link.download=`Diploma_Lenguaje_${level}_${name.replace(/\s+/g,"_")}.png`;link.href=canvas.toDataURL("image/png");link.click()};return <Shell {...{unit,level,stage}}><section className="language-reward"><div className="language-reward-rays"/><motion.div className="language-feather" animate={{y:[0,-14,0],rotate:[-5,5,-5]}} transition={{repeat:Infinity,duration:3}}>🪶</motion.div><small>{final?"COLECCIÓN COMPLETADA":"NUEVO COLECCIONABLE"}</small><h1>{final?`¡Guardían de las Palabras · ${getLanguageLevel(level).title}!`:feather}</h1><div className="language-reward-stars">{[1,2,3].map(i=><Star key={i} fill={i<=stars?"currentColor":"none"}/>)}</div><p>Tu biblioteca ganó <b>{unit.xp+stars*20} XP</b>, <b>{stars} estrellas</b> y una nueva pluma.</p>{final&&<button className="language-diploma" onClick={diploma}><Download/> Descargar diploma</button>}<div className="language-reward-actions"><button onClick={()=>navigate(`/language/${level}`)}><Home/> Volver al libro</button><button onClick={()=>navigate("/language")}><Award/> Ver portales</button></div></section></Shell>}
