import { useEffect, useRef, useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Award, CheckCircle2, ChevronRight, Download, Heart, Home, RotateCcw, Sparkles, Star } from "lucide-react";
import { motion } from "framer-motion";
import { getMathLevel, getMathUnit } from "../data/mathWorldData";
import { completeUnit, getLevelProgress, updateUnitProgress } from "../utils/progressManager";
import { getProfile } from "../utils/profileStorage";
import { useDemoAccount } from "../utils/demoAccess";
import "../styles/math-lesson.css";

const stageProgress={presentation:5,intro:20,examples:35,practice:50,game:68,quiz:85,result:92,reward:100};
const nextPath=(level,id,stage)=>({presentation:`/math/${level}/unit/${id}/lesson`,intro:`/math/${level}/unit/${id}/examples`,examples:`/math/${level}/unit/${id}/practice`,practice:`/math/${level}/unit/${id}/game`,game:`/math/${level}/unit/${id}/quiz`}[stage]);

function StageShell({unit,level,stage,children}){const navigate=useNavigate();return <main className={`math-lesson-screen game-${unit.gameType}`} style={{"--unit-color":unit.color}}><header className="math-lesson-top"><button onClick={()=>navigate(`/math/${level}`)}><ArrowLeft/> Mapa</button><div><span>Matemáticas · {getMathLevel(level).title}</span><b>{unit.title}</b></div><div className="math-lesson-stage"><span>{stageProgress[stage]}%</span><i><b style={{width:`${stageProgress[stage]}%`}}/></i></div></header>{children}</main>}

function Continue({onClick,label="Continuar"}){return <button className="math-primary" onClick={onClick}>{label}<ChevronRight/></button>}

export default function MathLessonStage({ stage }) {
  const {level="beginner",unitId="1"}=useParams(); const unit=getMathUnit(level,unitId); const navigate=useNavigate(); const location=useLocation();
  const demo=useDemoAccount();
  const beginnerDone=getLevelProgress("math","beginner").completedUnits.length;
  const intermediateDone=getLevelProgress("math","intermediate").completedUnits.length;
  const currentProgress=getLevelProgress("math",level);
  const levelAllowed=demo||level==="beginner"||(level==="intermediate"&&beginnerDone>=6)||(level==="advanced"&&beginnerDone>=6&&intermediateDone>=6);
  const unitAllowed=demo||(levelAllowed&&currentProgress.unlockedUnits.includes(unit.id));
  useEffect(()=>{if(!unitAllowed)navigate(`/math/${level}`,{replace:true})},[level,navigate,unitAllowed]);
  useEffect(()=>{if(unitAllowed&&stage!=="reward")updateUnitProgress("math",level,unit.id,stageProgress[stage]);},[level,stage,unit.id,unitAllowed]);
  if(!unitAllowed)return null;
  const go=()=>navigate(nextPath(level,unit.id,stage));
  if(stage==="presentation")return <StageShell {...{unit,level,stage}}><section className="math-presentation"><motion.div className="math-presentation-art" initial={{scale:.7,rotate:-5}} animate={{scale:1,rotate:0}}><img src={unit.image} alt=""/><span>{unit.icon}</span></motion.div><div><small>UNIDAD {unit.id} · NUEVA MISIÓN</small><h1>{unit.title}</h1><p>{unit.subtitle}</p><ul><li>Explicación clara y visual</li><li>Práctica guiada sin penalización</li><li>{unit.gameTitle}</li><li>Evaluación y recompensa</li></ul><Continue onClick={go} label="Comenzar aventura"/></div></section></StageShell>;
  if(stage==="intro")return <StageShell {...{unit,level,stage}}><section className="math-content-card"><span className="math-kicker"><Sparkles/> APRENDEMOS JUNTOS</span><h1>Descubre: {unit.title}</h1><div className="math-intro-grid"><div className="math-intro-copy">{unit.intro.map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><div className="math-intro-visual"><img src={unit.image} alt=""/><b>{unit.icon}</b></div></div><Continue onClick={go} label="Ver ejemplos"/></section></StageShell>;
  if(stage==="examples")return <StageShell {...{unit,level,stage}}><section className="math-content-card"><span className="math-kicker">👀 EJEMPLOS VISUALES</span><h1>Mira cómo funciona</h1><div className="math-example-grid">{unit.examples.map((example,index)=><motion.article key={example.title} initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:index*.1}}><div>{example.visual}</div><h2>{example.title}</h2><p>{example.text}</p></motion.article>)}</div><Continue onClick={go} label="Practicar conmigo"/></section></StageShell>;
  if(stage==="practice")return <Practice unit={unit} level={level} stage={stage} onDone={go}/>;
  if(stage==="game")return <Game unit={unit} level={level} stage={stage} onDone={go}/>;
  if(stage==="quiz")return <Quiz unit={unit} level={level} stage={stage}/>;
  if(stage==="result")return <Result unit={unit} level={level} stage={stage} state={location.state}/>;
  return <Reward unit={unit} level={level} stage="reward" state={location.state}/>;
}

function Practice({unit,level,stage,onDone}){const[index,setIndex]=useState(0),[picked,setPicked]=useState("");const item=unit.practice[index],correct=picked===item.answer;const next=()=>{if(index===unit.practice.length-1)onDone();else{setIndex(index+1);setPicked("")}};return <StageShell {...{unit,level,stage}}><section className="math-challenge-card"><span className="math-kicker">🧠 PRÁCTICA GUIADA · SIN PENALIZACIÓN</span><h1>{item.prompt}</h1><p>Intenta todas las veces que necesites. Aquí estamos aprendiendo.</p><div className="math-options">{item.options.map(option=><button key={option} className={picked?(option===item.answer?"correct":option===picked?"wrong":""):""} onClick={()=>setPicked(option)}>{option}</button>)}</div>{picked&&<div className={`math-feedback ${correct?"ok":"retry"}`}>{correct?<><CheckCircle2/> ¡Excelente! Encontraste la respuesta.</>:<><RotateCcw/> Casi. Observa el ejemplo e inténtalo otra vez.</>}</div>}{correct&&<Continue onClick={next} label={index===unit.practice.length-1?"Ir al minijuego":"Siguiente práctica"}/>}</section></StageShell>}

function Game({unit,level,stage,onDone}){const[index,setIndex]=useState(0),[score,setScore]=useState(0),[picked,setPicked]=useState("");const item=unit.game[index];const choose=(option)=>{if(picked)return;setPicked(option);if(option===item.answer)setScore(score+1)};const next=()=>{if(index===unit.game.length-1)onDone();else{setIndex(index+1);setPicked("")}};return <StageShell {...{unit,level,stage}}><section className="math-game-shell"><header><div className="math-game-icon">{unit.icon}</div><div><span>MINIJUEGO</span><h1>{unit.gameTitle}</h1></div><strong>{score}/{unit.game.length}</strong></header><div className="math-game-scene"><div className="math-game-decor">{unit.gameType==="balloons"?"🎈🎈🎈":unit.gameType==="pizza"?"🍕🍕":unit.gameType==="shop"?"🛒🏪":unit.gameType==="treasure"?"🗺️💎":"✨ ⭐ ✨"}</div><h2>{item.prompt}</h2><div className="math-options">{item.options.map(option=><button key={option} className={picked?(option===item.answer?"correct":option===picked?"wrong":""):""} onClick={()=>choose(option)}>{option}</button>)}</div>{picked&&<Continue onClick={next} label={index===unit.game.length-1?"Ir a la evaluación":"Siguiente reto"}/>}</div></section></StageShell>}

function Quiz({unit,level,stage}){const navigate=useNavigate();const[index,setIndex]=useState(0),[score,setScore]=useState(0),[hearts,setHearts]=useState(3),[picked,setPicked]=useState("");const item=unit.quiz[index];const choose=(option)=>{if(picked)return;setPicked(option);if(option===item.answer)setScore(score+1);else setHearts(Math.max(0,hearts-1))};const next=()=>{const finished=index===unit.quiz.length-1||hearts===0;if(finished)navigate(`/math/${level}/unit/${unit.id}/result`,{state:{score,total:unit.quiz.length}});else{setIndex(index+1);setPicked("")}};return <StageShell {...{unit,level,stage}}><section className="math-quiz-card"><header><span>Pregunta {index+1} de {unit.quiz.length}</span><div>{[0,1,2].map(i=><Heart key={i} fill={i<hearts?"currentColor":"none"}/>)}</div></header><div className="math-quiz-line"><i style={{width:`${(index+1)/unit.quiz.length*100}%`}}/></div><h1>{item.question}</h1><div className="math-options">{item.options.map(option=><button key={option} className={picked?(option===item.answer?"correct":option===picked?"wrong":""):""} onClick={()=>choose(option)}>{option}</button>)}</div>{picked&&<Continue onClick={next} label={index===unit.quiz.length-1||hearts===0?"Ver resultado":"Siguiente pregunta"}/>}</section></StageShell>}

function Result({unit,level,stage,state}){const navigate=useNavigate();const score=Number(state?.score||0),total=Number(state?.total||unit.quiz.length),pct=Math.round(score/total*100);return <StageShell {...{unit,level,stage}}><section className="math-result-card"><div className="math-result-ring" style={{"--score":`${pct*3.6}deg`}}><span>{pct}%</span></div><span className="math-kicker">RESULTADO DE LA MISIÓN</span><h1>{pct>=80?"¡Trabajo extraordinario!":pct>=60?"¡Muy buen esfuerzo!":"¡Cada intento te hace crecer!"}</h1><p>Respondiste correctamente <b>{score} de {total}</b> preguntas.</p><div className="math-result-details"><span>⭐ {pct>=90?3:pct>=70?2:1} estrellas</span><span>✨ +{unit.xp} XP</span><span>🪙 +20 monedas</span></div><Continue onClick={()=>navigate(`/math/${level}/unit/${unit.id}/reward`,{state:{score,total}})} label="Recibir recompensa"/></section></StageShell>}

function Reward({unit,level,stage,state}){const navigate=useNavigate();const once=useRef(false);const score=Number(state?.score||unit.quiz.length),total=Number(state?.total||unit.quiz.length),pct=Math.round(score/total*100),stars=pct>=90?3:pct>=70?2:1;useEffect(()=>{if(once.current)return;once.current=true;completeUnit("math",level,unit.id,stars,unit.xp+stars*20)},[level,stars,unit.id,unit.xp]);const final=unit.id===getMathLevel(level).units.length;const diploma=()=>{const name=getProfile()?.name||"Estudiante EduPlay",canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=1600;canvas.height=1100;const g=ctx.createLinearGradient(0,0,1600,1100);g.addColorStop(0,"#142b78");g.addColorStop(.5,"#6e35d5");g.addColorStop(1,"#0da8b5");ctx.fillStyle=g;ctx.fillRect(0,0,1600,1100);ctx.strokeStyle="#ffd85a";ctx.lineWidth=25;ctx.strokeRect(45,45,1510,1010);ctx.textAlign="center";ctx.fillStyle="#ffd85a";ctx.font="900 78px Georgia";ctx.fillText("EDUPLAY",800,180);ctx.fillStyle="white";ctx.font="700 48px Georgia";ctx.fillText(`DIPLOMA DE MATEMÁTICAS · ${getMathLevel(level).title.toUpperCase()}`,800,310);ctx.font="30px Arial";ctx.fillText("Se certifica que",800,415);ctx.fillStyle="#fff0a0";ctx.font="900 72px Georgia";ctx.fillText(name,800,540);ctx.fillStyle="white";ctx.font="28px Arial";ctx.fillText("completó con éxito las seis aventuras del nivel",800,650);ctx.fillStyle="#ffd85a";ctx.font="900 58px Arial";ctx.fillText("★ ★ ★",800,775);ctx.fillStyle="white";ctx.font="24px Arial";ctx.fillText(new Date().toLocaleDateString("es-GT"),800,920);const link=document.createElement("a");link.download=`Diploma_Matematicas_${level}_${name.replace(/\s+/g,"_")}.png`;link.href=canvas.toDataURL("image/png");link.click()};return <StageShell {...{unit,level,stage}}><section className="math-reward-card"><Sparkles className="math-reward-spark"/><div className="math-trophy">{final?"🏆":"🎁"}</div><span>{final?"NIVEL COMPLETADO":"MISIÓN COMPLETADA"}</span><h1>{final?`¡Dominaste Matemáticas ${getMathLevel(level).title}!`:`¡Completaste ${unit.title}!`}</h1><div className="math-stars">{[1,2,3].map(i=><Star key={i} fill={i<=stars?"currentColor":"none"}/>)}</div><p>Ganaste <b>{unit.xp+stars*20} XP</b>, <b>{stars} estrellas</b> y <b>20 monedas</b>.</p>{final&&<button className="math-diploma" onClick={diploma}><Download/> Descargar diploma</button>}<div className="math-reward-actions"><button onClick={()=>navigate(`/math/${level}`)}><Home/> Volver al mapa</button><button onClick={()=>navigate("/math")}><Award/> Ver niveles</button></div></section></StageShell>}
